import * as Lucide from 'lucide-react';
import type { LucideIcon, LucideProps } from 'lucide-react';

export type { LucideIcon };

export type Icon = LucideProps;

export const Add = Lucide.Plus;
export const AlertCircle = Lucide.AlertCircle;
export const ArrowLeft = Lucide.MoveLeft;
export const ArrowRight = Lucide.MoveRight;
export const Billing = Lucide.CreditCard;
export const Boxes = Lucide.Boxes;
export const Check = Lucide.Check;
export const ChevronDown = Lucide.ChevronDown;
export const ChevronLeft = Lucide.ChevronLeft;
export const ChevronRight = Lucide.ChevronRight;
export const ChevronsUpDown = Lucide.ChevronsUpDown;
export const CircleHelp = Lucide.CircleHelp;
export const Close = Lucide.X;
export const Copy = Lucide.Copy;
export const CopyDone = Lucide.ClipboardCheck;
export const Dashboard = Lucide.Activity;
export const Dot = Lucide.Dot;
export const Ellipsis = Lucide.MoreVertical;
export const Eye = Lucide.Eye;
export const EyeOff = Lucide.EyeOff;
export const Help = Lucide.HelpCircle;
export const Key = Lucide.Key;
export const LayoutGrid = Lucide.LayoutGrid;
export const LayoutList = Lucide.LayoutList;
export const ListTodo = Lucide.ListTodo;
export const LogIn = Lucide.LogIn;
export const Logo = Lucide.Command;
export const LogOut = Lucide.LogOut;
export const MenuIcon = Lucide.Menu;
export const Moon = Lucide.Moon;
export const Organization = Lucide.Building;
export const Page = Lucide.File;
export const PanelsTopLeft = Lucide.PanelsTopLeft;
export const Post = Lucide.FileText;
export const Settings = Lucide.Settings;
export const Spinner = Lucide.Loader2;
export const Sun = Lucide.SunMedium;
export const Trash = Lucide.Trash;
export const User = Lucide.User;
export const Users = Lucide.Users;
export const Warning = Lucide.AlertTriangle;
