import * as Lucide from 'lucide-react';
import type { LucideProps } from 'lucide-react';

export type Icon = LucideProps;

export const Add = Lucide.Plus;
export const AlertCircle = Lucide.AlertCircle;
export const ArrowLeft = Lucide.MoveLeft;
export const ArrowRight = Lucide.MoveRight;
export const Billing = Lucide.CreditCard;
export const Boxes = Lucide.Boxes;
export const Check = Lucide.Check;
export const ChevronLeft = Lucide.ChevronLeft;
export const ChevronRight = Lucide.ChevronRight;
export const ChevronsUpDown = Lucide.ChevronsUpDown;
export const CircleHelp = Lucide.CircleHelp;
export const Close = Lucide.X;
export const Copy = Lucide.Copy;
export const CopyDone = Lucide.ClipboardCheck;
export const Dashboard = Lucide.Activity;
export const Ellipsis = Lucide.MoreVertical;
export const Eye = Lucide.Eye;
export const EyeOff = Lucide.EyeOff;
export const Help = Lucide.HelpCircle;
export const Key = Lucide.Key;
export const LogIn = Lucide.LogIn;
export const Logo = Lucide.Command;
export const LogOut = Lucide.LogOut;
export const Moon = Lucide.Moon;
export const Organization = Lucide.Building;
export const Page = Lucide.File;
export const Post = Lucide.FileText;
export const Settings = Lucide.Settings;
export const Spinner = Lucide.Loader2;
export const Sun = Lucide.SunMedium;
export const Trash = Lucide.Trash;
export const User = Lucide.User;
export const Warning = Lucide.AlertTriangle;
