[build]
builder = "DOCKERFILE"
dockerfilePath = "/apps/web/Dockerfile"
buildEnvironment = "V2"

[deploy]
runtime = "V2"
numReplicas = 1
healthcheckPath = "/health-check"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
